name: Send Trigger To Botany Repository
on:
  release:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub dispatch event
        run: |
          curl --request POST 'https://api.github.com/repos/lcnem/botany/dispatches' \
          --header 'Authorization: Bearer ${{secrets.REPO_GITHUB_ACCESS_TOKEN}}' \
          --header 'Content-Type: application/json' \
          --data-raw '{
            "event_type": "repository-cosmoscan-new-release"
          }'
