name: CI Telescope Docker image
on:
  pull_request:
    paths:
      - "projects/main/**"
      - "projects/shared/**"
jobs:
  push_to_registry:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup variables
        id: variables
        run: echo "::set-output name=version::${GITHUB_REF##*/}"
      - name: Build only
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./projects/main/Dockerfile
          push: false
          tags: |
            ghcr.io/cauchye/telescope:${{ steps.variables.outputs.version }}
            ghcr.io/cauchye/telescope:latest
