name: Publish Docker image
on:
  release:
    types: [published]
  # 暫定的にPR時の発火を追加
  pull_request:
    paths:
      - 'projects/main/**'
      - 'projects/shared/**'
      - 'projects/monitor/**'
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Setup variables
        id: variables
        run: echo "::set-output name=version::${GITHUB_REF##*/}"
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./projects/monitor
          file: ./projects/monitor/Dockerfile
          push: true
          tags: |
            lcnem/telescope-monitor:${{ steps.variables.outputs.version }}
            lcnem/telescope-monitor:latest
          build-args: GO111MODULE=auto
