name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Setup variables
        id: variables
        run: echo "::set-output name=version::${GITHUB_REF##*/}"
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./projects/main/Dockerfile
          push: true
          tags: |
            lcnem/telescope:${{ steps.variables.outputs.version }}
            lcnem/telescope:latest
      - name: Create GitHub dispatch event
        run: |
          curl --request POST 'https://api.github.com/repos/lcnem/botany/dispatches' \
          --header 'Authorization: Bearer ${{secrets.REPO_GITHUB_ACCESS_TOKEN}}' \
          --header 'Content-Type: application/json' \
          --data-raw '{
            "event_type": "repository-telescope-new-release"
          }'
