name: Publish Monitor Docker image
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup variables
        id: variables
        run: echo "::set-output name=version::${GITHUB_REF##*/}"
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./projects/monitor
          file: ./projects/monitor/Dockerfile
          push: true
          tags: |
            ghcr.io/CauchyE/telescope-monitor:${{ steps.variables.outputs.version }}
            ghcr.io/CauchyE/telescope-monitor:latest
